# // для сервака
# services:
#   db:
#     image: postgres:15
#     environment:
#       - TZ=Europe/Moscow
#       - PGTZ=Europe/Moscow
#     container_name: price_tracker_db
#     env_file:
#       - .env
#     ports:
#       - "45432:5432"
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
#       interval: 10s
#       timeout: 5s
#       retries: 5
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     restart: always

#   app:
#     build: ./backend
#     ports:
#       - "8000:8000"
#     container_name: price_app_service
#     depends_on:
#       db:
#         condition: service_healthy
#     env_file:
#       - .env
#     environment:
#       DB_HOST: db
#     volumes:
#       - ./backend:/app/backend
#     init: true
#     ipc: host
#     command: >
#       sh -c "cd src && alembic upgrade head && python main.py"
  
#   frontend:
#     container_name: price_tracker_frontend
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     ports:
#       - "3000:80"
#     depends_on:
#       - app
#     environment:
#       VITE_API_URL: http://localhost:8000

# volumes:
#   postgres_data:
# // для для локалки
services:
  db:
    image: postgres:15
    environment:
      - TZ=Europe/Moscow
      - PGTZ=Europe/Moscow
    container_name: price_tracker_db
    env_file:
      - .env
    ports:
      - "45432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  app:
    build: ./backend
    container_name: price_app_service
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DB_HOST: db
    volumes:
      - ./backend:/app
    working_dir: /app/src
    init: true
    ipc: host
    command: >
      sh -c "alembic upgrade head && python main.py"
  
  frontend:
    container_name: price_tracker_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
    environment:
      VITE_API_URL: /api
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always

volumes:
  postgres_data: