"""add parse_interval and last_parse_at to users

Revision ID: 1cfb98fa0baf
Revises: ac468089755c
Create Date: 2026-04-13 13:25:07.566153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cfb98fa0baf'
down_revision: Union[str, Sequence[str], None] = 'ac468089755c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('parse_interval', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_parse_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_parse_at')
    op.drop_column('users', 'parse_interval')
    # ### end Alembic commands ###
