"""Fix DateTime

Revision ID: cdd971c71193
Revises: 6c0afe298735
Create Date: 2026-03-25 21:14:44.520549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdd971c71193'
down_revision: Union[str, Sequence[str], None] = '6c0afe298735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('price_history', 'parsed_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    
    op.alter_column('products', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               existing_nullable=True)
               
    op.alter_column('subscriptions', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('price_history', 'parsed_at', server_default=None)
    op.alter_column('products', 'created_at', server_default=None)
    op.alter_column('subscriptions', 'created_at', server_default=None)
    # ### end Alembic commands ###

