"""update db for table shop and product

Revision ID: d950766e9e0b
Revises: 4af3c42d3b3a
Create Date: 2026-04-10 19:22:34.075646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd950766e9e0b'
down_revision: Union[str, Sequence[str], None] = '4af3c42d3b3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'shops', ['domain'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shops', type_='unique')
    # ### end Alembic commands ###
